INSERT INTO countries (name, capital) VALUES
('Albania', 'Tirana'),
('Andorra', 'Andorra la Vella'),
('Armenia', 'Yerevan'),
('Austria', 'Vienna'),
('Azerbaijan', 'Baku'),
('Belarus', 'Minsk'),
('Belgium', 'Brussels'),
('Bosnia and Herzegovina', 'Sarajevo'),
('Bulgaria', 'Sofia'),
('Croatia', 'Zagreb'),
('Cyprus', 'Nicosia'),
('Czech Republic', 'Prague'),
('Denmark', 'Copenhagen'),
('Estonia', 'Tallinn'),
('Finland', 'Helsinki'),
('France', 'Paris'),
('Georgia', 'Tbilisi'),
('Germany', 'Berlin'),
('Greece', 'Athens'),
('Hungary', 'Budapest'),
('Iceland', 'Reykjavík'),
('Ireland', 'Dublin'),
('Italy', 'Rome'),
('Kazakhstan', 'Nur-Sultan'),
('Kosovo', 'Pristina'),
('Latvia', 'Riga'),
('Liechtenstein', 'Vaduz'),
('Lithuania', 'Vilnius'),
('Luxembourg', 'Luxembourg'),
('Malta', 'Valletta'),
('Moldova', 'Chișinău'),
('Monaco', 'Monaco'),
('Montenegro', 'Podgorica'),
('Netherlands', 'Amsterdam'),
('North Macedonia', 'Skopje'),
('Norway', 'Oslo'),
('Poland', 'Warsaw'),
('Portugal', 'Lisbon'),
('Romania', 'Bucharest'),
('Russia', 'Moscow'),
('San Marino', 'San Marino'),
('Serbia', 'Belgrade'),
('Slovakia', 'Bratislava'),
('Slovenia', 'Ljubljana'),
('Spain', 'Madrid'),
('Sweden', 'Stockholm'),
('Switzerland', 'Bern'),
('Turkey', 'Ankara'),
('Ukraine', 'Kyiv'),
('United Kingdom', 'London'),
('Vatican City', 'Vatican City'),
('Algeria', 'Algiers'),
('Angola', 'Luanda'),
('Benin', 'Porto-Novo'),
('Botswana', 'Gaborone'),
('Burkina Faso', 'Ouagadougou'),
('Burundi', 'Gitega'),
('Cabo Verde', 'Praia'),
('Cameroon', 'Yaoundé'),
('Central African Republic', 'Bangui'),
('Chad', 'N\'Djamena'),
('Comoros', 'Moroni'),
('Democratic Republic of the Congo', 'Kinshasa'),
('Republic of the Congo', 'Brazzaville'),
('Côte d\'Ivoire', 'Yamoussoukro'),
('Djibouti', 'Djibouti'),
('Egypt', 'Cairo'),
('Equatorial Guinea', 'Malabo'),
('Eritrea', 'Asmara'),
('Eswatini', 'Mbabane'),
('Ethiopia', 'Addis Ababa'),
('Gabon', 'Libreville'),
('Gambia', 'Banjul'),
('Ghana', 'Accra'),
('Guinea', 'Conakry'),
('Guinea-Bissau', 'Bissau'),
('Kenya', 'Nairobi'),
('Lesotho', 'Maseru'),
('Liberia', 'Monrovia'),
('Libya', 'Tripoli'),
('Madagascar', 'Antananarivo'),
('Malawi', 'Lilongwe'),
('Mali', 'Bamako'),
('Mauritania', 'Nouakchott'),
('Mauritius', 'Port Louis'),
('Morocco', 'Rabat'),
('Mozambique', 'Maputo'),
('Namibia', 'Windhoek'),
('Niger', 'Niamey'),
('Nigeria', 'Abuja'),
('Rwanda', 'Kigali'),
('São Tomé and Príncipe', 'São Tomé'),
('Senegal', 'Dakar'),
('Seychelles', 'Victoria'),
('Sierra Leone', 'Freetown'),
('Somalia', 'Mogadishu'),
('South Africa', 'Pretoria'),
('South Sudan', 'Juba'),
('Sudan', 'Khartoum'),
('Tanzania', 'Dodoma'),
('Togo', 'Lomé'),
('Tunisia', 'Tunis'),
('Uganda', 'Kampala'),
('Zambia', 'Lusaka'),
('Zimbabwe', 'Harare'),
('Australia', 'Canberra'),
('Fiji', 'Suva'),
('Kiribati', 'Tarawa'),
('Marshall Islands', 'Majuro'),
('Micronesia', 'Palikir'),
('Nauru', 'Yaren District'), 
('New Zealand', 'Wellington'),
('Palau', 'Ngerulmud'),
('Papua New Guinea', 'Port Moresby'),
('Samoa', 'Apia'),
('Solomon Islands', 'Honiara'),
('Tonga', 'Nukuʻalofa'),
('Tuvalu', 'Funafuti'),
('Vanuatu', 'Port Vila'),
('Afghanistan', 'Kabul'),
('Azerbaijan', 'Baku'),
('Bahrain', 'Manama'),
('Bangladesh', 'Dhaka'),
('Bhutan', 'Thimphu'),
('Brunei', 'Bandar Seri Begawan'),
('Cambodia', 'Phnom Penh'),
('China', 'Beijing'),
('Cyprus', 'Nicosia'),
('East Timor', 'Dili'),
('Georgia', 'Tbilisi'),
('India', 'New Delhi'),
('Indonesia', 'Jakarta'),
('Iran', 'Tehran'),
('Iraq', 'Baghdad'),
('Israel', 'Jerusalem'),
('Japan', 'Tokyo'),
('Jordan', 'Amman'),
('Kuwait', 'Kuwait City'),
('Kyrgyzstan', 'Bishkek'),
('Laos', 'Vientiane'),
('Lebanon', 'Beirut'),
('Malaysia', 'Kuala Lumpur'),
('Maldives', 'Malé'),
('Mongolia', 'Ulaanbaatar'),
('Myanmar', 'Naypyidaw'),
('Nepal', 'Kathmandu'),
('North Korea', 'Pyongyang'),
('Oman', 'Muscat'),
('Pakistan', 'Islamabad'),
('Palestine', 'Ramallah'),
('Philippines', 'Manila'),
('Qatar', 'Doha'),
('Saudi Arabia', 'Riyadh'),
('Singapore', 'Singapore'),
('South Korea', 'Seoul'),
('Sri Lanka', 'Sri Jayawardenepura Kotte'),
('Syria', 'Damascus'),
('Taiwan', 'Taipei'),
('Tajikistan', 'Dushanbe'),
('Thailand', 'Bangkok'),
('Turkmenistan', 'Ashgabat'),
('United Arab Emirates', 'Abu Dhabi'),
('Uzbekistan', 'Tashkent'),
('Vietnam', 'Hanoi'),
('Yemen', 'Sana\'a'),
('Canada', 'Ottawa'),
('Mexico', 'Mexico City'),
('United States', 'Washington, D.C.'),
('Belize', 'Belmopan'),
('Costa Rica', 'San José'),
('El Salvador', 'San Salvador'),
('Guatemala', 'Guatemala City'),
('Honduras', 'Tegucigalpa'),
('Nicaragua', 'Managua'),
('Panama', 'Panama City'),
('Antigua and Barbuda', 'Saint John\'s'),
('Bahamas', 'Nassau'),
('Barbados', 'Bridgetown'),
('Cuba', 'Havana'),
('Dominica', 'Roseau'),
('Dominican Republic', 'Santo Domingo'),
('Grenada', 'St. George\'s'),
('Haiti', 'Port-au-Prince'),
('Jamaica', 'Kingston'),
('Saint Kitts and Nevis', 'Basseterre'),
('Saint Lucia', 'Castries'),
('Saint Vincent and the Grenadines', 'Kingstown'),
('Trinidad and Tobago', 'Port of Spain'),
('Argentina', 'Buenos Aires'),
('Bolivia', 'Sucre'),
('Brazil', 'Brasília'),
('Chile', 'Santiago'),
('Colombia', 'Bogotá'),
('Ecuador', 'Quito'),
('Guyana', 'Georgetown'),
('Paraguay', 'Asunción'),
('Peru', 'Lima'),
('Suriname', 'Paramaribo'),
('Uruguay', 'Montevideo'),
('Venezuela', 'Caracas');